name: deploy

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]

jobs:
  deploy:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'master' }}

    runs-on: ubuntu-latest

    steps:
      - name: execute remote ssh & deploy backend server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
                cd /home/ec2-user/easystudyBE/
                docker-compose down
                docker pull ${{ secrets.DOCKER_USERNAME }}/easystudy:latest
                docker-compose up --build -d
