name: deploy

on:
  workflow_run:
    workflows: ["build"]     # 위의 CI 워크플로우 name과 정확히 일치
    types: [completed]
    branches:
      - 'master'
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: execute remote ssh & deploy backend server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ec2-user/easystudyBE/
            docker pull ${{ secrets.DOCKER_USERNAME }}/easystudy:latest
            docker-compose down
            docker-compose up --build -d
